// Code generated by cue_gen. DO NOT EDIT.
package i_user_profile

import (
	"time"

	"cloud.google.com/go/spanner"
)

// Table の名前を定義
const TableName = "i_user_profile"

// カラム名の定義
const (
	ColumnBio       = "bio"
	ColumnCreatedAt = "created_at"
	ColumnProfileId = "profile_id"
	ColumnUpdatedAt = "updated_at"
	ColumnUserId    = "user_id"
	ColumnWebsite   = "website"
)

// プライマリーキー・カラムの配列
var (
	PrimaryKeys = []string{
		ColumnProfileId,
	}
	Columns = []string{
		ColumnBio,
		ColumnCreatedAt,
		ColumnProfileId,
		ColumnUpdatedAt,
		ColumnUserId,
		ColumnWebsite,
	}
)

// モデル定義
type Model struct {
	// 自己紹介
	Bio string `json:"bio" db:"bio"`
	// 生成日時
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	// プロフィールID
	ProfileId string `json:"profile_id" db:"profile_id"`
	// 更新日時
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	// ユーザーID
	UserId string `json:"user_id" db:"user_id"`
	// ウェブサイトURL
	Website string `json:"website" db:"website"`
}

// NewModel - 新規作成
func New(
	ProfileId string,
	Bio string,
	UserId string,
	Website string,
) *Model {
	return &Model{
		ProfileId: ProfileId,
		Bio:       Bio,
		UserId:    UserId,
		Website:   Website,
	}
}

// Insert 用 Mutation
func (m *Model) InsertMutation() *spanner.Mutation {
	return spanner.Insert(
		TableName,
		Columns,
		[]interface{}{
			m.Bio, m.CreatedAt, m.ProfileId, m.UpdatedAt, m.UserId, m.Website,
		},
	)
}

// Update 用 Mutation
func (m *Model) UpdateMutation() *spanner.Mutation {
	return spanner.Update(
		TableName,
		Columns,
		[]interface{}{
			m.Bio, m.CreatedAt, m.ProfileId, m.UpdatedAt, m.UserId, m.Website,
		},
	)
}

// Delete 用 Mutation
func (m *Model) DeleteMutation() *spanner.Mutation {
	pk := spanner.Key{
		m.ProfileId,
	}
	return spanner.Delete(TableName, pk)
}

// Bind - Spanner Row を構造体にマッピング
func (m *Model) Bind(row *spanner.Row) error {
	return row.ToStruct(m)
}
