// Code generated by cue_gen. DO NOT EDIT.
package i_user_profile

import (
	"cloud.google.com/go/spanner"
)

// Models - モデルのスライス
type Models []*Model

// TableName - テーブル名を取得
func (ms Models) TableName() string {
	return TableName
}

// Columns - カラム一覧を取得
func (ms Models) Columns() []string {
	return Columns
}

// PrimaryKeys - プライマリーキー一覧を取得
func (ms Models) PrimaryKeys() []string {
	return PrimaryKeys
}

// Bind - Spanner Row を `Models` にバインド
func (ms *Models) Bind(row *spanner.Row) error {
	m := &Model{}
	if err := m.Bind(row); err != nil {
		return err
	}
	*ms = append(*ms, m)
	return nil
}

// InsertMutations - まとめて Insert 用の Mutation を生成
func (ms Models) InsertMutations() []*spanner.Mutation {
	mutations := make([]*spanner.Mutation, len(ms))
	for i, m := range ms {
		mutations[i] = m.InsertMutation()
	}
	return mutations
}

// UpdateMutations - まとめて Update 用の Mutation を生成
func (ms Models) UpdateMutations() []*spanner.Mutation {
	mutations := make([]*spanner.Mutation, len(ms))
	for i, m := range ms {
		mutations[i] = m.UpdateMutation()
	}
	return mutations
}

// DeleteMutations - まとめて Delete 用の Mutation を生成
func (ms Models) DeleteMutations() []*spanner.Mutation {
	mutations := make([]*spanner.Mutation, len(ms))
	for i, m := range ms {
		mutations[i] = m.DeleteMutation()
	}
	return mutations
}
