@startuml

!include custom_er_style.puml
ER_COMMENT(自動生成)
  INFORMATION_ENTITY(user, ユーザー, user){
      + string user_id : -- ユーザーID
      --
      timestamp created_at : -- 生成日時
      string email : -- メールアドレス
      string name : -- 名前
      timestamp updated_at : -- 更新日時
  }
  
  INFORMATION_ENTITY(user_profile, ユーザープロフィール情報, user){
      + string profile_id : -- プロフィールID
      --
      string bio : -- 自己紹介
      timestamp created_at : -- 生成日時
      timestamp updated_at : -- 更新日時
      string user_id : -- ユーザーID
      string website : -- ウェブサイトURL
  }
  
  RELATION(user, ||--||, user_profile, user_id, user_id)

@enduml
